version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo



  # api-gt-motive:
  #   platform: linux/amd64
  #   image: gtmotive.estimate.microservice:latest
  #   build:
  #     context: .
  #     dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
  #   ports:
  #     - "5000:80"
  #     - "5001:443"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - MongoDb__ConnectionString=mongodb://mongo:27017
  #     - MongoDb__MongoDbDatabaseName=GtMotive
  #     - ASPNETCORE_hostBuilder__reloadConfigOnChange=false
  #   depends_on:
  #     - mongo

volumes:
  mongo-data: