version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
      
  gtmotive.estimate.microservice.host:
    platform: linux/amd64
    image: gtmotive.estimate.microservice:latest
    build:
      context: ..
      dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
    depends_on:
      - mongo

volumes:
  mongo-data: